spring:
  application:
    name: Insurance Service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:insurance_service}
    username: ${DB_USERNAME:insurance_app}
    password: ${DB_PASSWORD:insurance_app_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

# Auth0 Configuration
auth0:
  enabled: ${AUTH0_ENABLED:false} # Set to true to enable Auth0 integration
  domain: ${AUTH0_DOMAIN:} # your-domain.auth0.com
  api-token: ${AUTH0_API_TOKEN:} # your-api-token
  client-id: ${AUTH0_CLIENT_ID:} # your-client-id
  client-secret: ${AUTH0_CLIENT_SECRET:} # your-client-secret
  audience: ${AUTH0_AUDIENCE:} # https://your-domain.auth0.com/api/v2/
  timeout: ${AUTH0_TIMEOUT:10000} # Default timeout in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info}
        
