spring:
  config:
    import: optional:file:.env
  application:
    name: Insurance Service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:insurance_service}
    username: ${DB_USERNAME:insurance_app}
    password: ${DB_PASSWORD:insurance_app_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          auth0:
            issuer-uri: https://${AUTH0_DOMAIN}/
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}/
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info}
springdoc:
  swagger-ui:
    oauth:
      client-id: ${AUTH0_CLIENT_ID}
      use-pkce-with-authorization-code-grant: true
      additional-query-string-params:
        audience: ${AUTH0_AUDIENCE}
